In [66]:
# Third party
import importlib
import torch
import matplotlib.pyplot as plt

# User
import importlib
import base.encode
import attention
importlib.reload(base.encode)
importlib.reload(attention)

from base.encode import get_encoder_decoder
from attention import AttentionHead


In [2]:
encoder, decoder = get_encoder_decoder(training_data="../data/shakespear.txt", type='character')
encoder("Would you")

[35, 53, 59, 50, 42, 1, 63, 53, 59]

In [3]:
# let's now encode the entire text dataset and store it into a torch.Tensor
with open("../data/shakespear.txt", 'r', encoding='utf-8') as f:
    text = f.read()
data = torch.tensor(encoder(text), dtype=torch.long)

In [69]:

torch.set_printoptions(sci_mode=False)


data = "Would you"
input_length = len(data)
input_embedding_dim = 2

encoded_input = encoder(data)
input_embedded = torch.randn(size=(len(data), input_embedding_dim), dtype=torch.float64)
encoded_input, input_embedded, input_embedded.shape



([35, 53, 59, 50, 42, 1, 63, 53, 59],
 tensor([[-0.4347, -1.3366],
         [ 1.8144, -0.6323],
         [-1.5828,  0.8516],
         [ 0.1660, -1.2911],
         [ 1.1486, -0.8606],
         [-1.5051,  1.3237],
         [-0.3302,  0.2649],
         [ 1.4611, -0.0145],
         [ 0.4822,  0.7296]], dtype=torch.float64),
 torch.Size([9, 2]))

In [70]:

# 9x2  2x3 -> 9x3 * 3x9
out_dimension = 3
a = AttentionHead(input_embedding_dim, out_dimension, block_type="decoder")

embeddings, scores = a(input_embedded) #9x3

# 9x2 (Input) x 2x3 queries/keys -> 2x9 (Input) x 9x3 (All inputs transposed)  = 2x7 (Inputs weighted)
# 9x7 (Q) x 9x7 (K) -> 9x7 7x9 (Inputs weighted x inputs weighted) -> 9x9 (Final input matrix)
# 9x9 x 9x3 -> 9x3
embeddings, scores

(tensor([[ 0.7021,  1.1265, -0.2485],
         [ 0.7015,  1.1229, -0.2499],
         [ 0.2763, -1.5404, -1.2742],
         [-0.3931,  1.1916,  1.2198],
         [-0.3896,  1.1910,  1.2149],
         [ 0.2805, -1.5157, -1.2651],
         [ 0.3364, -0.8746, -0.9579],
         [-0.3318,  0.8022,  0.9089],
         [ 0.2040, -1.3677, -1.0775]], dtype=torch.float64),
 tensor([[    1.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,
              0.0000,     0.0000,     0.0000],
         [    0.9986,     0.0014,     0.0000,     0.0000,     0.0000,     0.0000,
              0.0000,     0.0000,     0.0000],
         [    0.0003,     0.9997,     0.0000,     0.0000,     0.0000,     0.0000,
              0.0000,     0.0000,     0.0000],
         [    0.0023,     0.0000,     0.9975,     0.0001,     0.0000,     0.0000,
              0.0000,     0.0000,     0.0000],
         [    0.0051,     0.0000,     0.9943,     0.0006,     0.0000,     0.0000,
              0.0000,     0.0000,    