In [18]:
# Third party
import importlib
import torch
import matplotlib.pyplot as plt

# User
import importlib
import base.encode
import attention
importlib.reload(base.encode)
importlib.reload(attention)

from encode import get_text_encoder_decoder
from attention import AttentionHead


In [14]:
encoder, decoder = get_text_encoder_decoder(training_data="../data/shakespear.txt", type='character')
encoder("Would you")

[35, 53, 59, 50, 42, 1, 63, 53, 59]

In [11]:
# let's now encode the entire text dataset and store it into a torch.Tensor
with open("../data/shakespear.txt", 'r', encoding='utf-8') as f:
    text = f.read()
data = torch.tensor(encoder(text), dtype=torch.long)

In [16]:

torch.set_printoptions(sci_mode=False)


data = "Would you"
input_length = len(data)
input_embedding_dim = 2

encoded_input = encoder(data)
input_embedded = torch.randn(size=(len(data), input_embedding_dim))
encoded_input, input_embedded, input_embedded.shape



([35, 53, 59, 50, 42, 1, 63, 53, 59],
 tensor([[-0.1124,  1.0991],
         [ 1.3969, -0.7540],
         [-1.7231,  0.6022],
         [-1.1804, -0.8145],
         [ 0.7465,  1.0205],
         [ 1.3840,  0.1378],
         [ 0.7970,  0.4135],
         [-0.8225,  2.6812],
         [ 0.4293, -1.4945]]),
 torch.Size([9, 2]))

In [19]:

# 9x2  2x3 -> 9x3 * 3x9
out_dimension = 3
a = AttentionHead(input_embedding_dim, out_dimension)

embeddings, scores = a(input_embedded) #9x3

# 9x2 (Input) x 2x3 queries/keys -> 2x9 (Input) x 9x3 (All inputs transposed)  = 2x7 (Inputs weighted)
# 9x7 (Q) x 9x7 (K) -> 9x7 7x9 (Inputs weighted x inputs weighted) -> 9x9 (Final input matrix)
# 9x9 x 9x3 -> 9x3
embeddings, scores

(tensor([[ 0.1388, -0.7002, -0.7948],
         [-4.7058,  3.7383, -1.3091],
         [ 2.1729, -1.8441,  0.4379],
         [ 2.2805, -1.4257,  1.1797],
         [-2.1123,  1.0593, -1.4617],
         [-4.6526,  3.6978, -1.2918],
         [-3.6543,  2.8511, -1.0898],
         [ 0.0156, -0.6871, -0.9489],
         [-4.3369,  3.4907, -1.1423]]),
 tensor([[    0.0018,     0.0109,     0.0652,     0.6645,     0.0006,     0.0015,
              0.0020,     0.0002,     0.2532],
         [    0.0018,     0.0000,     0.0000,     0.0000,     0.0034,     0.0001,
              0.0002,     0.9944,     0.0000],
         [    0.0000,     0.0085,     0.0002,     0.1363,     0.0000,     0.0001,
              0.0000,     0.0000,     0.8548],
         [    0.0088,     0.3990,     0.0029,     0.0283,     0.0240,     0.1352,
              0.0523,     0.0006,     0.3490],
         [    0.0492,     0.0082,     0.4832,     0.2840,     0.0153,     0.0073,
              0.0156,     0.1026,     0.0345],
         [ 